from datetime import datetime, timezone, timedelta
from models import Thread, Message

_now = datetime.now(timezone.utc)
_d = lambda days: _now - timedelta(days=days)
_f = lambda days: _now + timedelta(days=days)
_h = lambda hours: _now - timedelta(hours=hours)


THREADS: list[Thread] = [
    Thread(id="t1", subject="Q2 budget review — need your sign-off", sender="cfo@acme.com",
           sender_name="Rachel Kim", preview="Hi, attached is the Q2 budget draft. We need approval before Friday.",
           project="Finance", urgency_score=92, date=_d(0), is_read=False, due_date=_f(2),
           tags=["budget", "approval"],
           messages=[
               Message(id="t1m1", sender="cfo@acme.com", sender_name="Rachel Kim", date=_h(3), is_self=False,
                       body="Hi, attached is the Q2 budget draft for your review. We're tracking about 12% over on engineering headcount and need your sign-off before Friday's board prep meeting. Key items to focus on are slides 4–7 which cover the variance breakdown. Let me know if you have questions before then."),
               Message(id="t1m2", sender="me@acme.com", sender_name="You", date=_h(2), is_self=True,
                       body="Thanks Rachel. I've reviewed slides 4–7 and the headcount variance makes sense given the two senior hires we made in March. Can we schedule 30 minutes Thursday afternoon to walk through the rest before I formally sign off?"),
               Message(id="t1m3", sender="cfo@acme.com", sender_name="Rachel Kim", date=_h(1), is_self=False,
                       body="Thursday works perfectly — I'll send a 30-minute hold for 2pm. The only other flag is the infrastructure cost line which is also up due to the AWS spike we're investigating separately. I'll have an update on that before we meet."),
           ]),

    Thread(id="t2", subject="Production incident: API latency spike", sender="ops@acme.com",
           sender_name="Ops Bot", preview="Alert: p99 latency exceeded 2s threshold for 10+ minutes.",
           project="Engineering", urgency_score=98, date=_d(0), is_read=False,
           tags=["incident", "urgent"],
           messages=[
               Message(id="t2m1", sender="ops@acme.com", sender_name="Ops Bot", date=_h(5), is_self=False,
                       body="Alert: p99 latency exceeded 2s threshold for 10+ minutes starting at 14:32 UTC. Affected endpoints: /api/v2/export, /api/v2/search. No errors observed, but significant performance degradation. On-call engineer has been paged. Incident thread open at #inc-2024-0412."),
               Message(id="t2m2", sender="me@acme.com", sender_name="You", date=_h(4), is_self=True,
                       body="On it. Checking database query logs now — seeing some long-running queries on the export endpoint, all above 1.8s. This looks related to the index migration we ran this morning. The new index on export_jobs may not have finished building on the replica."),
               Message(id="t2m3", sender="ops@acme.com", sender_name="Ops Bot", date=_h(3), is_self=False,
                       body="Update: p99 latency returned to normal at 15:08 UTC. Root cause confirmed: missing index on export_jobs.created_at on read replica. Fix deployed. Total incident duration: 36 minutes. Post-mortem due Friday."),
           ]),

    Thread(id="t3", subject="Interview feedback needed — senior eng candidate", sender="hr@acme.com",
           sender_name="Dana Lee", preview="Could you submit your scorecard for Alex M. by EOD?",
           project="Hiring", urgency_score=75, date=_d(1), is_read=True, due_date=_f(1),
           tags=["hiring"],
           messages=[
               Message(id="t3m1", sender="hr@acme.com", sender_name="Dana Lee", date=_d(1), is_self=False,
                       body="Hi! Could you submit your scorecard for Alex M. by EOD today? The hiring committee meets tomorrow morning at 10am and we need all panel scores to proceed to the offer stage. Alex interviewed for the Senior Engineer role on your team — the system design and debugging rounds were with you."),
               Message(id="t3m2", sender="me@acme.com", sender_name="You", date=_h(18), is_self=True,
                       body="Just submitted the scorecard — strong yes from me. Alex's system design was the best I've seen this cycle: clean thinking about trade-offs and no hand-waving on failure modes. The debugging exercise was also excellent. Happy to discuss in the committee call."),
               Message(id="t3m3", sender="hr@acme.com", sender_name="Dana Lee", date=_h(17), is_self=False,
                       body="Perfect, thank you! The committee now has all scores. The call is tomorrow at 10am — I'll send the calendar invite in the next hour. If things go as expected, we'd want to move to offer by end of week."),
           ]),

    Thread(id="t4", subject="Re: Partnership proposal — follow up", sender="biz@partnercorp.com",
           sender_name="Mark Torres", preview="Following up on our conversation last week about the integration.",
           project="BD", urgency_score=60, date=_d(1), is_read=True,
           tags=["partnership"],
           messages=[
               Message(id="t4m1", sender="biz@partnercorp.com", sender_name="Mark Torres", date=_d(3), is_self=False,
                       body="Hi, following up on our conversation last week about the data integration. Our engineering team has reviewed the API spec and we're ready to move forward technically. The main open question is around data residency — we'll need all EU customer data to remain within EU borders to comply with our DPA. Is that something your infrastructure currently supports?"),
               Message(id="t4m2", sender="me@acme.com", sender_name="You", date=_d(2), is_self=True,
                       body="Thanks for the follow-up, Mark. EU data residency is fully supported — we have a Frankfurt region that handles all EU customer data with no cross-region transfer. I'll connect you with our solutions engineering team to get the technical details documented properly. What's your target timeline for the integration launch?"),
               Message(id="t4m3", sender="biz@partnercorp.com", sender_name="Mark Torres", date=_d(1), is_self=False,
                       body="Great to hear! We're targeting a Q3 launch, so ideally we'd finalize the integration spec by end of June. Happy to schedule time with your solutions engineering team — any day next week works on our end. We're very excited about this partnership."),
           ]),

    Thread(id="t5", subject="Design review: new onboarding flow", sender="design@acme.com",
           sender_name="Priya Shah", preview="Sharing the updated Figma for the onboarding redesign. Would love your thoughts.",
           project="Product", urgency_score=45, date=_d(2), is_read=True, due_date=_f(3),
           tags=["design", "review"],
           messages=[
               Message(id="t5m1", sender="design@acme.com", sender_name="Priya Shah", date=_d(2), is_self=False,
                       body="Hey! Sharing the updated Figma for the onboarding redesign: figma.com/file/abc123. The big change from v1 is we've collapsed the 5-step wizard into a 3-step flow based on the user research findings last month. Would love your thoughts on the progress screens in particular — there's some disagreement on the team about whether we need them at all."),
               Message(id="t5m2", sender="me@acme.com", sender_name="You", date=_d(1), is_self=True,
                       body="Love the simplified flow — the 5-step version always felt like too much friction before the user had seen any value. On the progress screens: I'd keep the first one (account setup confirmation) and cut the rest. Users just want to get to the product, and the intermediate screens feel like we're narrating something obvious."),
               Message(id="t5m3", sender="design@acme.com", sender_name="Priya Shah", date=_d(1), is_self=False,
                       body="That's the direction I was leaning too — I'll make that change and share the final version Thursday. Dev handoff is scheduled for Monday so we have some buffer. Thanks for the quick turnaround!"),
           ]),

    Thread(id="t6", subject="AWS bill spike — 40% increase this month", sender="billing@aws.amazon.com",
           sender_name="AWS Billing", preview="Your estimated charges for April are $14,200, up from $10,100.",
           project="Engineering", urgency_score=80, date=_d(2), is_read=False,
           tags=["cost", "infra"],
           messages=[
               Message(id="t6m1", sender="billing@aws.amazon.com", sender_name="AWS Billing", date=_d(2), is_self=False,
                       body="Your estimated charges for April 2024 are $14,200.00, compared to $10,100.00 in March — an increase of approximately 40.6%. Primary cost drivers: EC2 On-Demand ($6,400, +28%), S3 Data Transfer Out ($3,100, +180%), CloudWatch Logs Ingestion ($1,200, +95%). Your next invoice will be issued on May 1."),
               Message(id="t6m2", sender="me@acme.com", sender_name="You", date=_d(1), is_self=True,
                       body="The S3 transfer spike is the main anomaly. Digging into the logs — found it: a CloudFront distribution was misconfigured last Tuesday and has been bypassing the CDN cache entirely, hitting the S3 origin on every request. That explains the 180% increase. Fixing the cache behavior now, should be resolved within the hour."),
               Message(id="t6m3", sender="me@acme.com", sender_name="You", date=_d(1), is_self=True,
                       body="Fix is deployed. CloudFront cache hit rate is back to 94%. Posting a note in #engineering-ops with a runbook so this doesn't happen again. The May bill should return to the $10k range."),
           ]),

    Thread(id="t7", subject="CS 189 — Assignment 4 grades posted", sender="no-reply@university.edu",
           sender_name="University Portal", preview="Your grade for Assignment 4 has been posted. Check the portal.",
           project="School", urgency_score=55, date=_d(0), is_read=False,
           tags=["grades"],
           messages=[
               Message(id="t7m1", sender="no-reply@university.edu", sender_name="University Portal", date=_h(6), is_self=False,
                       body="Your grade for CS 189 Assignment 4 has been posted to the course portal. You can view your score and instructor comments by logging in at portal.university.edu. If you believe there is a grading error, please contact your instructor within 7 days of this notification."),
               Message(id="t7m2", sender="me@university.edu", sender_name="You", date=_h(4), is_self=True,
                       body="Hi Professor Chen, I just reviewed my Assignment 4 grade (82/100). I believe the grader may have missed my derivation in part 3b — it continues on the back of page 4. I've double-checked and the work is there. Could you take a look when you get a chance? I'm happy to come to office hours if easier."),
               Message(id="t7m3", sender="chen@university.edu", sender_name="Prof. Chen", date=_h(2), is_self=False,
                       body="Hi, thanks for flagging this. You're right — the grader missed the continuation on the back of page 4. I've updated your score to 89/100 in the portal; it should reflect within the hour. Good catch, and solid work on that derivation."),
           ]),

    Thread(id="t8", subject="Study group — midterm prep Thursday 7pm", sender="classmate@university.edu",
           sender_name="Jamie Wu", preview="Hey, we're meeting in the library Thursday at 7 to go over linear algebra.",
           project="School", urgency_score=70, date=_d(1), is_read=True, due_date=_f(2),
           tags=["study", "midterm"],
           messages=[
               Message(id="t8m1", sender="classmate@university.edu", sender_name="Jamie Wu", date=_d(1), is_self=False,
                       body="Hey! We're meeting in the library Thursday at 7pm to go over the linear algebra and probability sections for the midterm. Should be about 6 of us. Are you in? Also, if you have the practice problems from lecture 12, could you bring those? A few people missed that class."),
               Message(id="t8m2", sender="me@university.edu", sender_name="You", date=_d(1), is_self=True,
                       body="I'm in! I have the lecture 12 problems — I'll print enough copies for everyone. Should we also work through the 2022 past exam? I found it on the course archive and it seems to overlap heavily with what Chen mentioned would be on this year's midterm."),
               Message(id="t8m3", sender="classmate@university.edu", sender_name="Jamie Wu", date=_h(20), is_self=False,
                       body="Yes, definitely add the 2022 exam to the agenda — great find. I'll tell the rest of the group. See you Thursday at 7!"),
           ]),

    Thread(id="t9", subject="Internship offer from Stripe — please respond by May 2", sender="recruiting@stripe.com",
           sender_name="Stripe Recruiting", preview="We're thrilled to extend you an offer for our summer engineering internship.",
           project="Career", urgency_score=95, date=_d(1), is_read=False, due_date=_f(4),
           tags=["offer", "deadline"],
           messages=[
               Message(id="t9m1", sender="recruiting@stripe.com", sender_name="Stripe Recruiting", date=_d(1), is_self=False,
                       body="We're thrilled to extend you an offer for the Summer 2024 Software Engineering Internship on the Payments Infrastructure team in San Francisco. Details: Start date June 10, compensation $9,500/month, housing stipend $2,000. Your full offer letter is attached. Please respond by May 2 — we'd love to have you on the team!"),
               Message(id="t9m2", sender="me@university.edu", sender_name="You", date=_h(22), is_self=True,
                       body="Thank you so much for the offer — I'm genuinely excited about the Payments Infrastructure team. Before I formally accept, I have two quick questions: (1) Is there any flexibility on the start date? My finals run through June 7 and I'd love a few days of buffer. (2) Is it possible to work remotely for the first week while I arrange housing in SF?"),
               Message(id="t9m3", sender="recruiting@stripe.com", sender_name="Stripe Recruiting", date=_h(20), is_self=False,
                       body="Great questions! We can adjust your start date to June 12 — that gives you a few days after finals to settle in. For the first week, your manager is open to remote work while you get housing sorted. We're really looking forward to having you join the team. Let us know your decision by May 2!"),
           ]),

    Thread(id="t10", subject="Sublet listing — room available May 1 near campus", sender="roomie@gmail.com",
           sender_name="Alex Chen", preview="I'm looking for someone to sublet my room May–August, $900/mo.",
           project=None, urgency_score=30, date=_d(3), is_read=True,
           tags=[],
           messages=[
               Message(id="t10m1", sender="roomie@gmail.com", sender_name="Alex Chen", date=_d(3), is_self=False,
                       body="Hi! I'm looking for someone to sublet my room May 1 through August 31. It's $900/month, utilities included. The apartment is a 2BR, 10-minute walk from the engineering quad, fully furnished. My other roommate is a grad student — very chill, mostly works from home. Let me know if you're interested and I can show you the place this week!"),
               Message(id="t10m2", sender="me@university.edu", sender_name="You", date=_d(2), is_self=True,
                       body="Hey Alex, this sounds perfect for my summer timeline! Is the $900 at all negotiable if I commit to the full May–August term? I'd also love to know: is there parking available, and what's the WiFi situation like for working from home?"),
               Message(id="t10m3", sender="roomie@gmail.com", sender_name="Alex Chen", date=_d(2), is_self=False,
                       body="For the full term I could do $875 — that works for me. No dedicated parking unfortunately, but street parking on Oak St is usually easy to find. WiFi is 1Gbps fiber, no issues working from home. Want to come see it Saturday morning?"),
           ]),

    Thread(id="t11", subject="PR review requested: auth middleware refactor", sender="github@github.com",
           sender_name="GitHub", preview="@you was requested to review a pull request by @sarah-dev.",
           project="Engineering", urgency_score=65, date=_d(0), is_read=False,
           tags=["pr", "review"],
           messages=[
               Message(id="t11m1", sender="github@github.com", sender_name="GitHub", date=_h(7), is_self=False,
                       body="@sarah-dev has requested your review on PR #847: 'Refactor auth middleware to use JWT validation service'. 12 files changed, +340 −180 lines. The PR description notes this is a prerequisite for the OAuth2 provider work planned for next sprint. View the pull request at github.com/acme/api/pull/847."),
               Message(id="t11m2", sender="me@acme.com", sender_name="You", date=_h(5), is_self=True,
                       body="Reviewed. Overall the approach is solid and the test coverage is good. Main concern: the token refresh logic in middleware/auth.js around line 142 doesn't handle concurrent refresh requests — if two requests arrive simultaneously with an expired token, you'll get two refresh calls and one will fail. Everything else looks great."),
               Message(id="t11m3", sender="sarah@acme.com", sender_name="Sarah (sarah-dev)", date=_h(3), is_self=False,
                       body="Great catch on the concurrent refresh issue — that's a real edge case we'd have hit in production. I've implemented a request coalescing pattern (same approach as the cache layer) and added a test that simulates concurrent expiry. Can you re-review when you get a chance? Should be a quick pass."),
           ]),

    Thread(id="t12", subject="Terraform plan diff — staging deploy", sender="ci@acme.com",
           sender_name="CI Bot", preview="Terraform plan complete. 3 resources to add, 1 to destroy. Approval needed.",
           project="Engineering", urgency_score=70, date=_d(0), is_read=False,
           tags=["infra", "approval"],
           messages=[
               Message(id="t12m1", sender="ci@acme.com", sender_name="CI Bot", date=_h(4), is_self=False,
                       body="Terraform plan complete for staging environment. Summary: 3 resources to add (aws_rds_instance.analytics, aws_elasticache_cluster.session, aws_security_group.analytics-db), 1 to destroy (aws_security_group.legacy-db). Estimated monthly cost change: +$180. Full plan at ci.acme.com/runs/tf-8821. Manual approval required to apply."),
               Message(id="t12m2", sender="me@acme.com", sender_name="You", date=_h(3), is_self=True,
                       body="The RDS and ElastiCache additions look correct — those are for the analytics pipeline we kicked off last sprint. One question before I approve: is the destruction of legacy-db security group intentional? I want to confirm it's not a drift issue before we apply."),
               Message(id="t12m3", sender="ci@acme.com", sender_name="CI Bot", date=_h(2), is_self=False,
                       body="Confirmed: the legacy-db security group deletion is intentional. @devops-lead marked it for removal last week — it's being replaced by the new analytics-db group in this plan. @devops-lead has approved on their end. Awaiting your approval to proceed with apply."),
           ]),

    Thread(id="t13", subject="Quarterly board deck — first draft", sender="ceo@acme.com",
           sender_name="Sarah Chen (CEO)", preview="Attaching the first draft of the Q2 board deck. Please review slides 8–12.",
           project="Finance", urgency_score=85, date=_d(1), is_read=True, due_date=_f(5),
           tags=["board", "review"],
           messages=[
               Message(id="t13m1", sender="ceo@acme.com", sender_name="Sarah Chen (CEO)", date=_d(1), is_self=False,
                       body="Team, attaching the first draft of the Q2 board deck. I need everyone to review slides 8–12 which cover engineering metrics and the infrastructure cost narrative. The board has been asking pointed questions about reliability since last quarter's incidents, so we need the latency improvement story to be airtight. Feedback due Thursday EOD — the board meeting is Tuesday."),
               Message(id="t13m2", sender="me@acme.com", sender_name="You", date=_h(20), is_self=True,
                       body="Reviewed slides 8–12. Three notes: (1) Slide 9's p99 latency graph should start from January 1 — starting in March undersells the full improvement arc. (2) Slide 11 shows $10.1k/month for infra costs but April came in at $14.2k due to the CloudFront issue (now fixed — May will be back to normal). That needs a callout. (3) The reliability narrative is strong otherwise — the incident response time stats are compelling."),
               Message(id="t13m3", sender="ceo@acme.com", sender_name="Sarah Chen (CEO)", date=_h(18), is_self=False,
                       body="Perfect — exactly what I needed. Updating the latency graph date range now and I'll get the corrected April infra number from Rachel with the CloudFront fix context. Final deck goes out Monday morning. Thank you!"),
           ]),

    Thread(id="t14", subject="User research session — can you join Thursday?", sender="ux@acme.com",
           sender_name="Jordan Kim", preview="We have 3 user research sessions Thursday 2–5pm. Would love an eng observer.",
           project="Product", urgency_score=40, date=_d(2), is_read=True, due_date=_f(2),
           tags=["research"],
           messages=[
               Message(id="t14m1", sender="ux@acme.com", sender_name="Jordan Kim", date=_d(2), is_self=False,
                       body="Hi! We have three back-to-back user research sessions Thursday from 2–5pm, testing the new onboarding flow with users who struggled with the original design. It would be really valuable to have an engineer observing — you'd watch via Lookback (not in the room). The sessions are specifically with users who hit the friction points you and Priya identified. Can you make it?"),
               Message(id="t14m2", sender="me@acme.com", sender_name="You", date=_d(1), is_self=True,
                       body="Thursday 2–5 works for me — blocking it now. Should I join the Lookback session silently, or is there a separate observer channel? Also, is there a debrief afterward? I'd love to hear the team's read on what we saw."),
               Message(id="t14m3", sender="ux@acme.com", sender_name="Jordan Kim", date=_d(1), is_self=False,
                       body="Join silently via Lookback — I'll send the link Wednesday afternoon. We have a 30-minute debrief at 5:30 if you can stay. Having engineering in the debrief is really valuable since some of the friction points may have implementation implications. See you Thursday!"),
           ]),

    Thread(id="t15", subject="Security audit findings — action items", sender="security@acme.com",
           sender_name="Security Team", preview="Sharing the pen test results. 2 high-severity findings need immediate attention.",
           project="Engineering", urgency_score=90, date=_d(1), is_read=False,
           tags=["security", "urgent"],
           messages=[
               Message(id="t15m1", sender="security@acme.com", sender_name="Security Team", date=_d(1), is_self=False,
                       body="Sharing the results of the external pen test completed last week. Two high-severity findings require immediate attention: (1) Stored XSS in the admin dashboard comment field — CVSS 8.2, exploitable by any admin user. (2) Insecure Direct Object Reference in /api/documents — CVSS 9.1, allows authenticated users to access other users' files by manipulating the document ID. Full report attached. Please assign owners and remediation deadlines by EOW."),
               Message(id="t15m2", sender="me@acme.com", sender_name="You", date=_h(22), is_self=True,
                       body="Assigning: (1) XSS in admin comment field → @frontend-team, target fix April 28. (2) IDOR in /api/documents → @backend-team, target fix April 25 (higher severity, expediting). Both added to the security board as P0. I'll send a status update Friday and we'll do a second review before either fix ships to production."),
               Message(id="t15m3", sender="security@acme.com", sender_name="Security Team", date=_h(20), is_self=False,
                       body="Confirmed — findings tracker updated with assignees and dates. Please note the IDOR issue is particularly critical as it affects any authenticated user, not just admins. Ensure the fix includes a regression test and gets a second engineer review before deploy. Let me know if you need help scoping the fix."),
           ]),

    Thread(id="t16", subject="Re: Async vs sync API design — RFC", sender="eng@acme.com",
           sender_name="Dev Mailing List", preview="Continuing the thread on whether the new export API should be sync or async.",
           project="Engineering", urgency_score=35, date=_d(4), is_read=True,
           tags=["rfc"],
           messages=[
               Message(id="t16m1", sender="eng@acme.com", sender_name="Dev Mailing List", date=_d(4), is_self=False,
                       body="Continuing the RFC thread on the new export API design. Original proposal: async with job ID (fire-and-forget, clients poll a /status endpoint). Counter-proposal: sync with streaming response (clients consume chunked transfer encoding). The thread has 14 replies. We need a decision before sprint planning Monday — both approaches are technically viable."),
               Message(id="t16m2", sender="me@acme.com", sender_name="You", date=_d(3), is_self=True,
                       body="My vote is async with job ID. The streaming approach is elegant but it adds significant complexity to every client — they'd all need to handle partial responses, reconnection logic, and half-received payloads. With async, clients just poll a simple status endpoint. The added latency of 1–2 extra roundtrips is acceptable given the export sizes we're targeting (minutes, not seconds)."),
               Message(id="t16m3", sender="eng@acme.com", sender_name="Dev Mailing List", date=_d(3), is_self=False,
                       body="Update: @mike-eng and @priya-backend align with async. @sarah-dev prefers streaming but accepts async if we commit to a webhook option for push-based clients. Decision: async with job ID, webhook support added to Q3 backlog. Thanks all — this is locked. Sprint planning is Monday at 10am."),
           ]),

    Thread(id="t17", subject="Visa appointment confirmation — June 3", sender="consulate@gov.example",
           sender_name="Consulate Booking", preview="Your appointment is confirmed for June 3 at 9:00am. Bring original documents.",
           project="Personal", urgency_score=88, date=_d(5), is_read=True, due_date=_f(36),
           tags=["visa", "important"],
           messages=[
               Message(id="t17m1", sender="consulate@gov.example", sender_name="Consulate Booking", date=_d(5), is_self=False,
                       body="Your visa appointment is confirmed for June 3 at 9:00 AM at 123 Consulate Ave, San Francisco, CA 94105. Required documents: original passport, this confirmation email, completed DS-160 form (print confirmation page), one passport-sized photo (white background), financial documents (bank statements, employment letter). Processing time is typically 2–4 weeks. Do not arrive more than 15 minutes early."),
               Message(id="t17m2", sender="me@gmail.com", sender_name="You", date=_d(4), is_self=True,
                       body="Hey, just got my visa appointment confirmation for June 3. Can you come with me for moral support? I want to make sure I have all my documents in order — do I need to bring original bank statements or are certified copies acceptable? I've heard it varies by consulate."),
               Message(id="t17m3", sender="family@gmail.com", sender_name="Sam (family)", date=_d(4), is_self=False,
                       body="Of course I'll come! From my experience, they strongly prefer originals for financial documents, but certified copies are usually accepted with a cover letter explaining why. I'd call the consulate's helpline Monday morning to confirm — they're usually helpful. I'll pick you up at 8am so we have plenty of time."),
           ]),

    Thread(id="t18", subject="Lunch Tuesday? Catching up on the new role", sender="friend@gmail.com",
           sender_name="Mia Rodriguez", preview="Hey! Heard you started the new job — would love to hear about it over lunch.",
           project=None, urgency_score=20, date=_d(3), is_read=True,
           tags=[],
           messages=[
               Message(id="t18m1", sender="friend@gmail.com", sender_name="Mia Rodriguez", date=_d(3), is_self=False,
                       body="Hey! Heard through the grapevine that you started the new role last month — congrats, that's so exciting! Would love to catch up over lunch and hear how it's going. Are you free any day next week? I'm flexible Tuesday through Thursday. Miss you!"),
               Message(id="t18m2", sender="me@gmail.com", sender_name="You", date=_d(2), is_self=True,
                       body="Mia! Yes, the new role has been incredible — so much to catch up on. Tuesday at noon works perfectly for me. Have you tried that new ramen spot on 5th that just opened? Been wanting to check it out."),
               Message(id="t18m3", sender="friend@gmail.com", sender_name="Mia Rodriguez", date=_d(2), is_self=False,
                       body="Tuesday noon is perfect! I haven't been to the ramen place yet but I've heard the tonkotsu broth is amazing. I'll make a reservation now. Can't wait to hear everything — see you Tuesday!"),
           ]),

    Thread(id="t19", subject="Contract renewal — SaaS vendor", sender="renewals@vendor.com",
           sender_name="Vendor Sales", preview="Your annual contract expires May 15. Renewing now locks in your current rate.",
           project="Finance", urgency_score=72, date=_d(2), is_read=False, due_date=_f(17),
           tags=["contract", "renewal"],
           messages=[
               Message(id="t19m1", sender="renewals@vendor.com", sender_name="Vendor Sales", date=_d(2), is_self=False,
                       body="Hi, your annual contract for DataSync Pro expires on May 15, 2024. Renewing before the expiration date locks in your current rate of $2,400/year for all 25 seats. After May 15, the renewal price increases to $3,200/year due to our updated pricing tier. To renew, click the link below or reply to this email. Questions? Contact your account manager Sarah at sarah@vendor.com."),
               Message(id="t19m2", sender="me@acme.com", sender_name="You", date=_d(1), is_self=True,
                       body="Hi Sarah, before we renew I'd like to discuss the contract. We're currently using about 14 of the 25 seats — roughly 56% utilization. Is there a smaller tier that might be a better fit? Also, we've been a customer for 3 years — is there a loyalty discount available on renewal?"),
               Message(id="t19m3", sender="renewals@vendor.com", sender_name="Vendor Sales", date=_d(1), is_self=False,
                       body="Thanks for reaching out! We do have a 15-seat plan at $1,800/year that would suit your usage much better. For customers with 3+ years, I can apply an additional 10% loyalty discount — bringing it to $1,620/year, a significant reduction from either option. I'll send over a revised quote today. Would you like to hop on a quick call to go over it?"),
           ]),

    Thread(id="t20", subject="Hackathon this weekend — team forming", sender="club@university.edu",
           sender_name="CS Club", preview="TreeHacks is this Friday–Sunday. We still have spots on the team if you're interested.",
           project="School", urgency_score=50, date=_d(1), is_read=True, due_date=_f(3),
           tags=["hackathon"],
           messages=[
               Message(id="t20m1", sender="club@university.edu", sender_name="CS Club", date=_d(1), is_self=False,
                       body="TreeHacks is this Friday through Sunday at the Engineering Quad. Our club team has 3 open spots and we'd love to have you join. We're thinking something in the AI/productivity space — no idea fully formed yet, which is part of the fun. Last year's team made it to the top 10 out of 300+ teams. Interested? Reply by Wednesday to lock in your spot."),
               Message(id="t20m2", sender="me@university.edu", sender_name="You", date=_d(1), is_self=True,
                       body="Count me in! I've been wanting to do TreeHacks for ages. What's the vibe — competitive grind or more relaxed? I'm happy to lead the AI/ML side if that's useful; I've been working a lot with LLM APIs lately and have a few ideas we could prototype quickly."),
               Message(id="t20m3", sender="club@university.edu", sender_name="CS Club", date=_h(20), is_self=False,
                       body="Amazing — so excited to have you! The vibe is competitive but healthy: we work hard during the hack but genuinely celebrate whatever we ship. Leading the AI/ML side would be perfect — that's exactly the gap we had last year. Team kickoff call is Thursday at 8pm, I'll send a Zoom link. See you then!"),
           ]),
]

THREADS_BY_ID: dict[str, Thread] = {t.id: t for t in THREADS}
