from models import Transaction

TRANSACTIONS: list[Transaction] = [
    # ── Income ────────────────────────────────────────────────────────────────
    Transaction(id="t001", date="2026-05-01", amount=5200.00, merchant="Acme Corp", category="Income",
                account="Chase Checking", description="Salary deposit", type="income"),
    Transaction(id="t002", date="2026-04-01", amount=5200.00, merchant="Acme Corp", category="Income",
                account="Chase Checking", description="Salary deposit", type="income"),
    Transaction(id="t003", date="2026-03-01", amount=5200.00, merchant="Acme Corp", category="Income",
                account="Chase Checking", description="Salary deposit", type="income"),
    Transaction(id="t004", date="2026-02-01", amount=5200.00, merchant="Acme Corp", category="Income",
                account="Chase Checking", description="Salary deposit", type="income"),
    Transaction(id="t005", date="2026-04-15", amount=800.00, merchant="Freelance Client", category="Income",
                account="Chase Checking", description="Contract work payment", type="income", tags=["freelance"]),

    # ── Housing ───────────────────────────────────────────────────────────────
    Transaction(id="t006", date="2026-05-01", amount=2200.00, merchant="Parkside Apartments", category="Housing",
                account="Chase Checking", description="May rent", type="expense"),
    Transaction(id="t007", date="2026-04-01", amount=2200.00, merchant="Parkside Apartments", category="Housing",
                account="Chase Checking", description="April rent", type="expense"),
    Transaction(id="t008", date="2026-03-01", amount=2200.00, merchant="Parkside Apartments", category="Housing",
                account="Chase Checking", description="March rent", type="expense"),
    Transaction(id="t009", date="2026-02-01", amount=2200.00, merchant="Parkside Apartments", category="Housing",
                account="Chase Checking", description="February rent", type="expense"),
    Transaction(id="t010", date="2026-04-15", amount=87.40, merchant="PG&E", category="Housing",
                account="Chase Checking", description="Electricity bill", type="expense"),
    Transaction(id="t011", date="2026-04-05", amount=65.00, merchant="Comcast", category="Housing",
                account="Amex Gold", description="Internet monthly", type="expense"),

    # ── Food & Drink ──────────────────────────────────────────────────────────
    Transaction(id="t012", date="2026-05-06", amount=143.22, merchant="Whole Foods", category="Food & Drink",
                account="Amex Gold", description="Weekly grocery run", type="expense", tags=["groceries"]),
    Transaction(id="t013", date="2026-05-04", amount=14.85, merchant="Chipotle", category="Food & Drink",
                account="Amex Gold", description="Lunch", type="expense"),
    Transaction(id="t014", date="2026-05-03", amount=8.50, merchant="Blue Bottle Coffee", category="Food & Drink",
                account="Amex Gold", description="Morning coffee", type="expense"),
    Transaction(id="t015", date="2026-04-20", amount=121.09, merchant="Trader Joe's", category="Food & Drink",
                account="Amex Gold", description="Weekly groceries", type="expense", tags=["groceries"]),
    Transaction(id="t016", date="2026-04-14", amount=210.45, merchant="Nobu", category="Food & Drink",
                account="Amex Gold", description="Birthday dinner", type="expense", tags=["dining", "special"],
                is_flagged=True),
    Transaction(id="t017", date="2026-04-07", amount=98.30, merchant="Whole Foods", category="Food & Drink",
                account="Amex Gold", description="Grocery run", type="expense", tags=["groceries"]),
    Transaction(id="t018", date="2026-04-03", amount=22.10, merchant="Shake Shack", category="Food & Drink",
                account="Amex Gold", description="Dinner", type="expense"),
    Transaction(id="t019", date="2026-03-28", amount=7.25, merchant="Starbucks", category="Food & Drink",
                account="Amex Gold", description="Coffee", type="expense"),
    Transaction(id="t020", date="2026-03-15", amount=88.60, merchant="Sprouts", category="Food & Drink",
                account="Amex Gold", description="Grocery run", type="expense", tags=["groceries"]),
    Transaction(id="t021", date="2026-03-08", amount=31.50, merchant="Pizza Hut", category="Food & Drink",
                account="Amex Gold", description="Dinner delivery", type="expense"),
    Transaction(id="t022", date="2026-02-22", amount=156.80, merchant="Whole Foods", category="Food & Drink",
                account="Amex Gold", description="Big grocery haul", type="expense", tags=["groceries"]),
    Transaction(id="t023", date="2026-02-14", amount=185.00, merchant="Chez Panisse", category="Food & Drink",
                account="Amex Gold", description="Valentine's dinner", type="expense", tags=["dining", "special"],
                is_flagged=True),

    # ── Transport ─────────────────────────────────────────────────────────────
    Transaction(id="t024", date="2026-05-05", amount=18.40, merchant="Uber", category="Transport",
                account="Amex Gold", description="Ride to airport", type="expense"),
    Transaction(id="t025", date="2026-04-28", amount=62.10, merchant="Shell", category="Transport",
                account="Chase Checking", description="Gas fill-up", type="expense"),
    Transaction(id="t026", date="2026-04-22", amount=24.50, merchant="Uber", category="Transport",
                account="Amex Gold", description="Evening ride", type="expense"),
    Transaction(id="t027", date="2026-03-30", amount=15.75, merchant="Lyft", category="Transport",
                account="Amex Gold", description="Ride home", type="expense"),
    Transaction(id="t028", date="2026-03-14", amount=58.40, merchant="Shell", category="Transport",
                account="Chase Checking", description="Gas fill-up", type="expense"),
    Transaction(id="t029", date="2026-02-28", amount=25.00, merchant="SP+ Parking", category="Transport",
                account="Chase Checking", description="Downtown parking", type="expense"),

    # ── Entertainment ─────────────────────────────────────────────────────────
    Transaction(id="t030", date="2026-05-02", amount=17.99, merchant="Netflix", category="Entertainment",
                account="Amex Gold", description="Monthly subscription", type="expense", tags=["subscription"]),
    Transaction(id="t031", date="2026-05-02", amount=11.99, merchant="Spotify", category="Entertainment",
                account="Amex Gold", description="Monthly subscription", type="expense", tags=["subscription"]),
    Transaction(id="t032", date="2026-04-19", amount=32.00, merchant="AMC Theatres", category="Entertainment",
                account="Amex Gold", description="Movie tickets x2", type="expense"),
    Transaction(id="t033", date="2026-04-12", amount=59.99, merchant="Steam", category="Entertainment",
                account="Amex Gold", description="Game purchase", type="expense"),
    Transaction(id="t034", date="2026-04-02", amount=17.99, merchant="Netflix", category="Entertainment",
                account="Amex Gold", description="Monthly subscription", type="expense", tags=["subscription"]),
    Transaction(id="t035", date="2026-04-02", amount=11.99, merchant="Spotify", category="Entertainment",
                account="Amex Gold", description="Monthly subscription", type="expense", tags=["subscription"]),
    Transaction(id="t036", date="2026-03-21", amount=145.00, merchant="Live Nation", category="Entertainment",
                account="Amex Gold", description="Concert tickets", type="expense", tags=["event"]),
    Transaction(id="t037", date="2026-03-02", amount=17.99, merchant="Netflix", category="Entertainment",
                account="Amex Gold", description="Monthly subscription", type="expense", tags=["subscription"]),

    # ── Subscriptions (SaaS/tools) ────────────────────────────────────────────
    Transaction(id="t038", date="2026-05-01", amount=43.20, merchant="AWS", category="Subscriptions",
                account="Chase Checking", description="Cloud hosting", type="expense", tags=["work"]),
    Transaction(id="t039", date="2026-04-01", amount=4.00, merchant="GitHub", category="Subscriptions",
                account="Chase Checking", description="Pro plan", type="expense", tags=["work"]),
    Transaction(id="t040", date="2026-04-15", amount=54.99, merchant="Adobe CC", category="Subscriptions",
                account="Amex Gold", description="Creative Cloud monthly", type="expense"),
    Transaction(id="t041", date="2026-04-01", amount=38.75, merchant="AWS", category="Subscriptions",
                account="Chase Checking", description="Cloud hosting", type="expense", tags=["work"]),
    Transaction(id="t042", date="2026-03-01", amount=4.00, merchant="GitHub", category="Subscriptions",
                account="Chase Checking", description="Pro plan", type="expense", tags=["work"]),

    # ── Shopping ──────────────────────────────────────────────────────────────
    Transaction(id="t043", date="2026-05-08", amount=89.47, merchant="Amazon", category="Shopping",
                account="Amex Gold", description="Desk accessories", type="expense"),
    Transaction(id="t044", date="2026-04-16", amount=174.90, merchant="Zara", category="Shopping",
                account="Amex Gold", description="Spring clothing", type="expense", is_flagged=True),
    Transaction(id="t045", date="2026-03-25", amount=33.99, merchant="Amazon", category="Shopping",
                account="Amex Gold", description="Phone case + cable", type="expense"),
    Transaction(id="t046", date="2026-03-10", amount=249.00, merchant="Best Buy", category="Shopping",
                account="Amex Gold", description="Mechanical keyboard", type="expense", is_flagged=True),

    # ── Health ────────────────────────────────────────────────────────────────
    Transaction(id="t047", date="2026-05-01", amount=25.00, merchant="Planet Fitness", category="Health",
                account="Chase Checking", description="Monthly membership", type="expense", tags=["subscription"]),
    Transaction(id="t048", date="2026-04-24", amount=42.15, merchant="CVS Pharmacy", category="Health",
                account="Amex Gold", description="Prescription refill", type="expense"),
    Transaction(id="t049", date="2026-04-01", amount=25.00, merchant="Planet Fitness", category="Health",
                account="Chase Checking", description="Monthly membership", type="expense", tags=["subscription"]),
    Transaction(id="t050", date="2026-03-18", amount=40.00, merchant="Dr. Kim's Office", category="Health",
                account="Chase Checking", description="Copay", type="expense"),
    Transaction(id="t051", date="2026-03-01", amount=25.00, merchant="Planet Fitness", category="Health",
                account="Chase Checking", description="Monthly membership", type="expense", tags=["subscription"]),
]

TRANSACTIONS_BY_ID = {t.id: t for t in TRANSACTIONS}
